@extends('technician.layout.app')

@section('content')

<!-- Top Navigation Bar -->
<nav class="w-full bg-white shadow-sm border-b border-gray-100 px-6 py-3 flex flex-wrap justify-between items-center mb-6">
  <!-- Left side -->
  <div class="flex items-center space-x-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
      class="w-6 h-6 text-blue-600">
      <path stroke-linecap="round" stroke-linejoin="round"
        d="M3 3v1m0 0a2 2 0 002 2h12a2 2 0 002-2V4m-2 16H5a2 2 0 01-2-2V4M3 4h18" />
    </svg>
    <h2 class="text-xl font-semibold text-gray-800">Reporting Dashboard</h2>
  </div>

  <!-- Right side -->
  <div class="flex items-center gap-3">
    <select class="px-3 py-2 border rounded-md text-sm focus:ring-blue-500 focus:border-blue-500">
      <option>This Week</option>
      <option>This Month</option>
      <option>Last 3 Months</option>
      <option>This Year</option>
    </select>

    <button class="bg-blue-600 text-white px-4 py-2 rounded-md text-sm hover:bg-blue-700">
      Export Report
    </button>
  </div>
</nav>


<!-- Main Reporting Content -->
<div class="flex flex-col space-y-6">

  <!-- Summary Cards -->
  <div class="grid md:grid-cols-4 sm:grid-cols-2 gap-6">
    <div class="bg-white border rounded-lg shadow-sm p-4 flex flex-col">
      <h4 class="text-sm font-medium text-gray-500 mb-1">Total Quotations</h4>
      <p class="text-2xl font-semibold text-gray-800">124</p>
      <span class="text-xs text-green-600 mt-1 flex items-center"><i class="fas fa-arrow-up mr-1"></i> +12% from last month</span>
    </div>

    <div class="bg-white border rounded-lg shadow-sm p-4 flex flex-col">
      <h4 class="text-sm font-medium text-gray-500 mb-1">Total Inquiries</h4>
      <p class="text-2xl font-semibold text-gray-800">86</p>
      <span class="text-xs text-red-600 mt-1 flex items-center"><i class="fas fa-arrow-down mr-1"></i> –5% from last period</span>
    </div>

    <div class="bg-white border rounded-lg shadow-sm p-4 flex flex-col">
      <h4 class="text-sm font-medium text-gray-500 mb-1">Approved Quotes</h4>
      <p class="text-2xl font-semibold text-gray-800">59</p>
      <span class="text-xs text-green-600 mt-1 flex items-center"><i class="fas fa-arrow-up mr-1"></i> +8% overall</span>
    </div>

    <div class="bg-white border rounded-lg shadow-sm p-4 flex flex-col">
      <h4 class="text-sm font-medium text-gray-500 mb-1">Revenue (USD)</h4>
      <p class="text-2xl font-semibold text-gray-800">$92,300</p>
      <span class="text-xs text-green-600 mt-1 flex items-center"><i class="fas fa-arrow-up mr-1"></i> +18% YTD</span>
    </div>
  </div>

  <!-- Charts Section -->
  <div class="grid md:grid-cols-2 gap-6">
    <!-- Left chart -->
    <div class="bg-white border rounded-lg shadow-sm p-4">
      <h3 class="font-semibold text-gray-700 mb-3">Monthly Quotations Overview</h3>
      <div class="flex items-center justify-center h-64 bg-gray-50 rounded-lg text-gray-400 text-sm">
        [Chart Placeholder: Quotation Volume by Month]
      </div>
    </div>

    <!-- Right chart -->
    <div class="bg-white border rounded-lg shadow-sm p-4">
      <h3 class="font-semibold text-gray-700 mb-3">Inquiry Conversion Rate</h3>
      <div class="flex items-center justify-center h-64 bg-gray-50 rounded-lg text-gray-400 text-sm">
        [Chart Placeholder: Conversion % Pie Chart]
      </div>
    </div>
  </div>

  <!-- Data Table -->
  <div class="bg-white border rounded-lg shadow-sm">
    <div class="p-4 border-b flex justify-between items-center">
      <h3 class="font-semibold text-gray-700">Recent Reports Summary</h3>
      <button class="text-blue-600 hover:underline text-sm">View All</button>
    </div>
    <div class="overflow-x-auto">
      <table class="w-full text-sm text-left">
        <thead class="bg-gray-100 text-gray-700">
          <tr>
            <th class="px-6 py-3">Report ID</th>
            <th class="px-6 py-3">Category</th>
            <th class="px-6 py-3">Generated By</th>
            <th class="px-6 py-3">Date</th>
            <th class="px-6 py-3">Status</th>
            <th class="px-6 py-3 text-right">Action</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr class="hover:bg-gray-50">
            <td class="px-6 py-4 font-medium text-gray-800">REP-2025-001</td>
            <td class="px-6 py-4">Quotation Summary</td>
            <td class="px-6 py-4">Admin User</td>
            <td class="px-6 py-4">2025-11-14</td>
            <td class="px-6 py-4"><span class="bg-green-100 text-green-700 text-xs px-2 py-1 rounded">Completed</span></td>
            <td class="px-6 py-4 text-right">
              <button class="text-blue-600 hover:underline text-sm">View PDF</button>
            </td>
          </tr>
          <tr class="hover:bg-gray-50">
            <td class="px-6 py-4 font-medium text-gray-800">REP-2025-002</td>
            <td class="px-6 py-4">Monthly Revenue</td>
            <td class="px-6 py-4">Technician</td>
            <td class="px-6 py-4">2025-11-12</td>
            <td class="px-6 py-4"><span class="bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded">Pending</span></td>
            <td class="px-6 py-4 text-right">
              <button class="text-gray-500 hover:text-red-600 text-sm">Delete</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>

@endsection
